// @ts-check

/** @type {Window & typeof globalThis & { __PINGUIN_CONFIG__?: Record<string, unknown> }} */
const runtimeWindow = window;
const rawConfig = runtimeWindow.__PINGUIN_CONFIG__ ?? {};

const normalizeUrl = (value) => {
  if (!value || typeof value !== "string") {
    return "";
  }
  return value.trim().replace(/\/$/, "");
};

const deriveDefaultApiBaseUrl = () => {
  try {
    const { protocol, hostname, port } = window.location;
    if (port === "8080") {
      return `${protocol}//${hostname}:8081/api`;
    }
    if (port && port.length > 0) {
      return `${protocol}//${hostname}:${port}/api`;
    }
    return `${protocol}//${hostname}/api`;
  } catch {
    return "/api";
  }
};

export const RUNTIME_CONFIG = Object.freeze({
  apiBaseUrl: normalizeUrl(rawConfig.apiBaseUrl) || deriveDefaultApiBaseUrl(),
  landingUrl: String(rawConfig.landingUrl || "/index.html"),
	tenantUrl: String(rawConfig.tenantUrl || "/tenants.html"),
  eventLogUrl: String(rawConfig.eventLogUrl || "/event-log.html"),
  smtpRelayUrl: String(rawConfig.smtpRelayUrl || "/smtp-relay.html"),
});

export const STRINGS = Object.freeze({
  appName: "Pinguin Notification Service",
  navigation: {
	tenants: "Tenants",
    eventLog: "Event log",
    smtpRelay: "SMTP relay",
  },
  landing: {
    eyebrow: "Delivery operations",
    headline: "Pinguin notification workspace",
    subheadline:
      "Review delivery events, manage schedules, and configure SMTP relay access from one compact workspace.",
    previewLabel: "Notification workspace preview",
    previewTitle: "Recent delivery events",
    previewState: "Live",
    previewItems: Object.freeze([
      Object.freeze({ status: "Queued", subject: "Welcome email", time: "09:30", variant: "queued" }),
      Object.freeze({ status: "Sent", subject: "SMS reminder", time: "10:15", variant: "sent" }),
      Object.freeze({ status: "Errored", subject: "Invoice notice", time: "11:00", variant: "errored" }),
    ]),
  },
	tenants: {
	  title: "Tenants",
	  subtitle: "Create and manage notification delivery tenants and API access.",
	  emptyState: "No tenants yet. Create the first tenant to start sending notifications.",
	  loadingState: "Loading tenants…",
	  loadError: "Unable to load tenants.",
	  createLabel: "Create tenant",
	  createTitle: "Create tenant",
	  createSuccess: "Tenant created",
	  createError: "Unable to create tenant. Check every required delivery field.",
	  updateLabel: "Manage tenant",
	  updateTitle: "Manage tenant",
	  updateSuccess: "Tenant configuration updated",
	  updateError: "Unable to update tenant configuration.",
	  deleteTitle: "Permanently delete tenant",
	  deleteDescription: "Permanently delete this tenant and every notification, delivery profile, API credential, and SMTP resource it owns?",
	  deleteSuccess: "Tenant permanently deleted",
	  deleteError: "Unable to delete tenant.",
	  rotateLabel: "Rotate API key",
	  rotateError: "Unable to rotate API key.",
	  createdKeyTitle: "Copy the new API key",
	  rotatedKeyTitle: "Copy the rotated API key",
	  keyDescription: "This key is shown once. Copy it before closing this dialog.",
	  copySuccess: "API key copied",
	  copyError: "Unable to copy API key.",
	  displayNameLabel: "Display name",
	  supportEmailLabel: "Support email",
	  emailProfileTitle: "External email delivery",
	  emailHostLabel: "SMTP host",
	  emailPortLabel: "SMTP port",
	  emailUsernameLabel: "SMTP username",
	  emailPasswordLabel: "SMTP password",
	  emailFromLabel: "From address",
	  smsEnabledLabel: "Configure SMS delivery",
	  smsAccountSIDLabel: "Twilio account SID",
	  smsAuthTokenLabel: "Twilio auth token",
	  smsFromLabel: "SMS from number",
	  credentialLabel: "API credential",
	  neverUsed: "Never used",
	},
  eventLog: {
    title: "Event log",
    subtitle: "Review delivery status, adjust schedules, or cancel queued jobs in a single view.",
    profileMenuLabel: "User menu",
    emptyState: "No notifications yet. Start by sending one via the CLI or gRPC client.",
    scheduleDialogTitle: "Reschedule notification",
    scheduleDialogDescription: "Select a new delivery time. Notifications can only be edited while queued.",
    cancelDialogTitle: "Cancel notification",
    cancelDialogDescription: "Cancel this queued notification and stop its delivery attempts?",
    cancelKeepLabel: "Keep notification",
    cancelActionLabel: "Cancel notification",
    scheduleSuccess: "Delivery time updated",
    cancelSuccess: "Notification cancelled",
    cancelError: "Unable to cancel notification.",
    rescheduleError: "Unable to reschedule notification.",
    loadError: "Unable to load notifications.",
    searchLabel: "Search",
    searchPlaceholder: "Search notifications",
    loadingMore: "Loading more notifications…",
    endOfResults: "All matching notifications loaded.",
    tenantLabel: "Tenant",
    tenantLoading: "Loading tenants…",
    tenantLoadError: "Unable to load tenants.",
    tenantRequired: "Select a tenant to view notifications.",
    statusFilterLabel: "Filter by status",
    loadedLabel: "loaded",
    createdLabel: "Created",
    scheduledLabel: "Scheduled",
    recipientLabel: "Recipient",
    tenantMetadataLabel: "Tenant",
    untitledLabel: "Untitled notification",
    loadingState: "Loading notifications…",
    deliveryTimeLabel: "Delivery time",
  },
  smtpIdentities: {
    title: "SMTP relay",
    subtitle: "Create shared sender credentials and reply forwarding.",
	tenantLabel: "Tenant",
	tenantLoadError: "Unable to load tenants.",
    domainSetupTitle: "Sender domains",
    domainSetupDescription: "Add a domain, publish its DNS records, and verify it before creating identities.",
    domainLabel: "Sending domain",
    domainPlaceholder: "example.com",
    domainRecordsLabel: "DNS records",
    domainHostColumn: "Host",
    domainTypeColumn: "Type",
    domainValueColumn: "Value",
    domainPurposeColumn: "Purpose",
    domainStatusColumn: "Status",
    domainPendingLabel: "Pending DNS",
    domainVerifiedLabel: "Verified",
    domainCheckLabel: "Check DNS",
    domainAddLabel: "Add domain",
    domainLoadingState: "Loading sender domains…",
    domainEmptyState: "Add a sender domain before creating SMTP credentials.",
    domainCreateSuccess: "Sender domain added",
    domainCheckSuccess: "DNS check completed",
    domainCreateError: "Unable to add sender domain.",
    domainCreateExistsError: "Sender domain is already registered.",
    domainCreateInvalidError: "Enter a valid sender domain.",
    domainLoadError: "Unable to load sender domains.",
    domainCheckError: "Unable to check DNS.",
    domainRequiredNotice: "Verify this sender domain before creating SMTP credentials.",
    domainExpandLabel: "Expand",
    domainCollapseLabel: "Collapse",
    domainLastCheckedLabel: "Last checked",
    domainNeverCheckedLabel: "Not checked",
    domainCheckPendingLabel: "Awaiting check",
    domainCheckPassedLabel: "DNS record matched",
    domainCheckFailedLabel: "DNS record is missing",
    domainCopyHostLabel: "Copy DNS host",
    domainCopyValueLabel: "Copy DNS value",
    domainCopyHostSuccess: "DNS host copied",
    domainCopyValueSuccess: "DNS value copied",
    outboundTitle: "Outbound credentials",
    inboundTitle: "Inbound fanout",
    identitiesTitle: "SMTP identities",
    identitiesDescription: "Manage sender credentials and forwarding owners.",
    createIdentityLabel: "Create identity",
    createIdentityTitle: "Create SMTP identity",
    createIdentityDescription: "Choose a verified sender domain and define where inbound copies are forwarded.",
    localPartLabel: "Local part",
    localPartPlaceholder: "alice",
    senderDomainLabel: "Sender domain",
    senderDomainPlaceholder: "Select a verified domain",
    emailLabel: "Sender address",
    emailPlaceholder: "name@example.com",
    forwardToLabel: "Forward copies to",
    forwardToPlaceholder: "owner@example.com\nmaria@example.com",
    forwardToDisplayLabel: "Forwarding owners",
    actionColumn: "Actions",
    loadingState: "Loading SMTP identities…",
    emptyState: "No SMTP identities yet.",
    loadError: "Unable to load SMTP identities.",
    credentialsLoadError: "Unable to load SMTP credentials.",
    createError: "Unable to create SMTP identity.",
    updateForwardingError: "Unable to update forwarding owners.",
    rotateError: "Unable to rotate SMTP credentials.",
    deleteError: "Unable to delete SMTP identity.",
    createSuccess: "SMTP identity created",
    credentialsLoadSuccess: "SMTP credentials loaded",
    updateForwardingSuccess: "Forwarding owners updated",
    rotateSuccess: "SMTP credentials rotated",
    deleteSuccess: "SMTP identity deleted",
    deleteDialogTitle: "Delete SMTP identity",
    deleteDialogDescription: "Delete this identity, its SMTP credentials, and its forwarding route?",
    deleteKeepLabel: "Keep identity",
    deleteActionLabel: "Delete identity",
    editForwardingLabel: "Edit forwarding owners",
    openCredentialsLabel: "Open Gmail SMTP settings for",
    cancelEditLabel: "Cancel edit",
    rotateConfirm: "Rotate credentials for this SMTP identity?",
    rotateCredentialsLabel: "Rotate credentials",
    credentialsTitle: "Gmail SMTP settings",
    credentialsDescription: "Use these current settings for Gmail Send-As.",
    credentialsCloseLabel: "Close Gmail SMTP settings",
    hostLabel: "SMTP server",
    hostCopyLabel: "Copy SMTP server",
    hostCopySuccess: "SMTP server copied",
    portLabel: "Port",
    securityLabel: "Security",
    usernameLabel: "Username",
    usernameCopyLabel: "Copy username",
    usernameCopySuccess: "Username copied",
    passwordLabel: "Password",
    passwordCopyLabel: "Copy password",
    passwordCopySuccess: "Password copied",
    copyError: "Unable to copy value.",
    lastUsedLabel: "Last used",
    neverUsed: "Never",
  },
  auth: {
    signingIn: "Preparing secure session…",
    ready: "Workspace ready",
    failed: "We could not reach the authentication service. Please retry.",
    loggedOut: "Session ended. Redirecting…",
  },
  actions: {
    refresh: "Refresh",
    reschedule: "Reschedule",
    cancel: "Cancel",
    saveChanges: "Save changes",
    close: "Close",
    logout: "Sign out",
    create: "Create",
    createIdentity: "Create identity",
    copy: "Copy",
    delete: "Delete",
  },
});

export const STATUS_LABELS = Object.freeze({
  queued: "Queued",
  sent: "Sent",
  errored: "Errored",
  cancelled: "Cancelled",
});

export const STATUS_OPTIONS = Object.freeze([
  { value: "all", label: "All statuses" },
  { value: "queued", label: STATUS_LABELS.queued },
  { value: "sent", label: STATUS_LABELS.sent },
  { value: "errored", label: STATUS_LABELS.errored },
  { value: "cancelled", label: STATUS_LABELS.cancelled },
]);
