// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pinguin.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumeration for notification type.
type NotificationType int32

const (
	NotificationType_EMAIL NotificationType = 0
	NotificationType_SMS   NotificationType = 1
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "EMAIL",
		1: "SMS",
	}
	NotificationType_value = map[string]int32{
		"EMAIL": 0,
		"SMS":   1,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pinguin_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_pinguin_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_pinguin_proto_rawDescGZIP(), []int{0}
}

// Enumeration for status.
type Status int32

const (
	Status_QUEUED    Status = 0
	Status_SENT      Status = 1
	Status_FAILED    Status = 2
	Status_UNKNOWN   Status = 3
	Status_CANCELLED Status = 4
	Status_ERRORED   Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "QUEUED",
		1: "SENT",
		2: "FAILED",
		3: "UNKNOWN",
		4: "CANCELLED",
		5: "ERRORED",
	}
	Status_value = map[string]int32{
		"QUEUED":    0,
		"SENT":      1,
		"FAILED":    2,
		"UNKNOWN":   3,
		"CANCELLED": 4,
		"ERRORED":   5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pinguin_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pinguin_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pinguin_proto_rawDescGZIP(), []int{1}
}

// Attachment metadata for email notifications.
type EmailAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAttachment) Reset() {
	*x = EmailAttachment{}
	mi := &file_pinguin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAttachment) ProtoMessage() {}

func (x *EmailAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_pinguin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAttachment.ProtoReflect.Descriptor instead.
func (*EmailAttachment) Descriptor() ([]byte, []int) {
	return file_pinguin_proto_rawDescGZIP(), []int{0}
}

func (x *EmailAttachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EmailAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *EmailAttachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request to send a notification.
type NotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationType NotificationType       `protobuf:"varint,1,opt,name=notification_type,json=notificationType,proto3,enum=pinguin.NotificationType" json:"notification_type,omitempty"`
	Recipient        string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject          string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"` // Optional for SMS.
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ScheduledTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	Attachments      []*EmailAttachment     `protobuf:"bytes,6,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_pinguin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinguin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_pinguin_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationRequest) GetNotificationType() NotificationType {
	if x != nil {
		return x.NotificationType
	}
	return NotificationType_EMAIL
}

func (x *NotificationRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *NotificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationRequest) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *NotificationRequest) GetAttachments() []*EmailAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// Response returned after sending (or when retrieving) a notification.
type NotificationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NotificationId    string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	NotificationType  NotificationType       `protobuf:"varint,2,opt,name=notification_type,json=notificationType,proto3,enum=pinguin.NotificationType" json:"notification_type,omitempty"`
	Recipient         string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject           string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Message           string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status            Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=pinguin.Status" json:"status,omitempty"`
	ProviderMessageId string                 `protobuf:"bytes,7,opt,name=provider_message_id,json=providerMessageId,proto3" json:"provider_message_id,omitempty"`
	RetryCount        int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ScheduledTime     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	Attachments       []*EmailAttachment     `protobuf:"bytes,12,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_pinguin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pinguin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_pinguin_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationResponse) GetNotificationType() NotificationType {
	if x != nil {
		return x.NotificationType
	}
	return NotificationType_EMAIL
}

func (x *NotificationResponse) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *NotificationResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_QUEUED
}

func (x *NotificationResponse) GetProviderMessageId() string {
	if x != nil {
		return x.ProviderMessageId
	}
	return ""
}

func (x *NotificationResponse) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *NotificationResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NotificationResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *NotificationResponse) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *NotificationResponse) GetAttachments() []*EmailAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// Request for retrieving the status.
type GetNotificationStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNotificationStatusRequest) Reset() {
	*x = GetNotificationStatusRequest{}
	mi := &file_pinguin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatusRequest) ProtoMessage() {}

func (x *GetNotificationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinguin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationStatusRequest) Descriptor() ([]byte, []int) {
	return file_pinguin_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

// Request for listing notifications.
type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []Status               `protobuf:"varint,1,rep,packed,name=statuses,proto3,enum=pinguin.Status" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_pinguin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinguin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_pinguin_proto_rawDescGZIP(), []int{4}
}

func (x *ListNotificationsRequest) GetStatuses() []Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// Response containing notifications for list requests.
type ListNotificationsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Notifications []*NotificationResponse `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_pinguin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pinguin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_pinguin_proto_rawDescGZIP(), []int{5}
}

func (x *ListNotificationsResponse) GetNotifications() []*NotificationResponse {
	if x != nil {
		return x.Notifications
	}
	return nil
}

// Request to reschedule a queued notification.
type RescheduleNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	ScheduledTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RescheduleNotificationRequest) Reset() {
	*x = RescheduleNotificationRequest{}
	mi := &file_pinguin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescheduleNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescheduleNotificationRequest) ProtoMessage() {}

func (x *RescheduleNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinguin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescheduleNotificationRequest.ProtoReflect.Descriptor instead.
func (*RescheduleNotificationRequest) Descriptor() ([]byte, []int) {
	return file_pinguin_proto_rawDescGZIP(), []int{6}
}

func (x *RescheduleNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *RescheduleNotificationRequest) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

// Request to cancel a queued notification.
type CancelNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelNotificationRequest) Reset() {
	*x = CancelNotificationRequest{}
	mi := &file_pinguin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelNotificationRequest) ProtoMessage() {}

func (x *CancelNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinguin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelNotificationRequest.ProtoReflect.Descriptor instead.
func (*CancelNotificationRequest) Descriptor() ([]byte, []int) {
	return file_pinguin_proto_rawDescGZIP(), []int{7}
}

func (x *CancelNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

var File_pinguin_proto protoreflect.FileDescriptor

const file_pinguin_proto_rawDesc = "" +
	"\n" +
	"\rpinguin.proto\x12\apinguin\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\x0fEmailAttachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xae\x02\n" +
	"\x13NotificationRequest\x12F\n" +
	"\x11notification_type\x18\x01 \x01(\x0e2\x19.pinguin.NotificationTypeR\x10notificationType\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12A\n" +
	"\x0escheduled_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x12:\n" +
	"\vattachments\x18\x06 \x03(\v2\x18.pinguin.EmailAttachmentR\vattachments\"\x90\x04\n" +
	"\x14NotificationResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12F\n" +
	"\x11notification_type\x18\x02 \x01(\x0e2\x19.pinguin.NotificationTypeR\x10notificationType\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12'\n" +
	"\x06status\x18\x06 \x01(\x0e2\x0f.pinguin.StatusR\x06status\x12.\n" +
	"\x13provider_message_id\x18\a \x01(\tR\x11providerMessageId\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12A\n" +
	"\x0escheduled_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x12:\n" +
	"\vattachments\x18\f \x03(\v2\x18.pinguin.EmailAttachmentR\vattachments\"G\n" +
	"\x1cGetNotificationStatusRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"G\n" +
	"\x18ListNotificationsRequest\x12+\n" +
	"\bstatuses\x18\x01 \x03(\x0e2\x0f.pinguin.StatusR\bstatuses\"`\n" +
	"\x19ListNotificationsResponse\x12C\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1d.pinguin.NotificationResponseR\rnotifications\"\x8b\x01\n" +
	"\x1dRescheduleNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12A\n" +
	"\x0escheduled_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\"D\n" +
	"\x19CancelNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId*&\n" +
	"\x10NotificationType\x12\t\n" +
	"\x05EMAIL\x10\x00\x12\a\n" +
	"\x03SMS\x10\x01*S\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\b\n" +
	"\x04SENT\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\v\n" +
	"\aUNKNOWN\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04\x12\v\n" +
	"\aERRORED\x10\x052\xdb\x03\n" +
	"\x13NotificationService\x12O\n" +
	"\x10SendNotification\x12\x1c.pinguin.NotificationRequest\x1a\x1d.pinguin.NotificationResponse\x12]\n" +
	"\x15GetNotificationStatus\x12%.pinguin.GetNotificationStatusRequest\x1a\x1d.pinguin.NotificationResponse\x12Z\n" +
	"\x11ListNotifications\x12!.pinguin.ListNotificationsRequest\x1a\".pinguin.ListNotificationsResponse\x12_\n" +
	"\x16RescheduleNotification\x12&.pinguin.RescheduleNotificationRequest\x1a\x1d.pinguin.NotificationResponse\x12W\n" +
	"\x12CancelNotification\x12\".pinguin.CancelNotificationRequest\x1a\x1d.pinguin.NotificationResponseB0Z.github.com/tyemirov/pinguin/pkg/grpcapi;grpcapib\x06proto3"

var (
	file_pinguin_proto_rawDescOnce sync.Once
	file_pinguin_proto_rawDescData []byte
)

func file_pinguin_proto_rawDescGZIP() []byte {
	file_pinguin_proto_rawDescOnce.Do(func() {
		file_pinguin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pinguin_proto_rawDesc), len(file_pinguin_proto_rawDesc)))
	})
	return file_pinguin_proto_rawDescData
}

var file_pinguin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pinguin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pinguin_proto_goTypes = []any{
	(NotificationType)(0),                 // 0: pinguin.NotificationType
	(Status)(0),                           // 1: pinguin.Status
	(*EmailAttachment)(nil),               // 2: pinguin.EmailAttachment
	(*NotificationRequest)(nil),           // 3: pinguin.NotificationRequest
	(*NotificationResponse)(nil),          // 4: pinguin.NotificationResponse
	(*GetNotificationStatusRequest)(nil),  // 5: pinguin.GetNotificationStatusRequest
	(*ListNotificationsRequest)(nil),      // 6: pinguin.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),     // 7: pinguin.ListNotificationsResponse
	(*RescheduleNotificationRequest)(nil), // 8: pinguin.RescheduleNotificationRequest
	(*CancelNotificationRequest)(nil),     // 9: pinguin.CancelNotificationRequest
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
}
var file_pinguin_proto_depIdxs = []int32{
	0,  // 0: pinguin.NotificationRequest.notification_type:type_name -> pinguin.NotificationType
	10, // 1: pinguin.NotificationRequest.scheduled_time:type_name -> google.protobuf.Timestamp
	2,  // 2: pinguin.NotificationRequest.attachments:type_name -> pinguin.EmailAttachment
	0,  // 3: pinguin.NotificationResponse.notification_type:type_name -> pinguin.NotificationType
	1,  // 4: pinguin.NotificationResponse.status:type_name -> pinguin.Status
	10, // 5: pinguin.NotificationResponse.scheduled_time:type_name -> google.protobuf.Timestamp
	2,  // 6: pinguin.NotificationResponse.attachments:type_name -> pinguin.EmailAttachment
	1,  // 7: pinguin.ListNotificationsRequest.statuses:type_name -> pinguin.Status
	4,  // 8: pinguin.ListNotificationsResponse.notifications:type_name -> pinguin.NotificationResponse
	10, // 9: pinguin.RescheduleNotificationRequest.scheduled_time:type_name -> google.protobuf.Timestamp
	3,  // 10: pinguin.NotificationService.SendNotification:input_type -> pinguin.NotificationRequest
	5,  // 11: pinguin.NotificationService.GetNotificationStatus:input_type -> pinguin.GetNotificationStatusRequest
	6,  // 12: pinguin.NotificationService.ListNotifications:input_type -> pinguin.ListNotificationsRequest
	8,  // 13: pinguin.NotificationService.RescheduleNotification:input_type -> pinguin.RescheduleNotificationRequest
	9,  // 14: pinguin.NotificationService.CancelNotification:input_type -> pinguin.CancelNotificationRequest
	4,  // 15: pinguin.NotificationService.SendNotification:output_type -> pinguin.NotificationResponse
	4,  // 16: pinguin.NotificationService.GetNotificationStatus:output_type -> pinguin.NotificationResponse
	7,  // 17: pinguin.NotificationService.ListNotifications:output_type -> pinguin.ListNotificationsResponse
	4,  // 18: pinguin.NotificationService.RescheduleNotification:output_type -> pinguin.NotificationResponse
	4,  // 19: pinguin.NotificationService.CancelNotification:output_type -> pinguin.NotificationResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pinguin_proto_init() }
func file_pinguin_proto_init() {
	if File_pinguin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pinguin_proto_rawDesc), len(file_pinguin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pinguin_proto_goTypes,
		DependencyIndexes: file_pinguin_proto_depIdxs,
		EnumInfos:         file_pinguin_proto_enumTypes,
		MessageInfos:      file_pinguin_proto_msgTypes,
	}.Build()
	File_pinguin_proto = out.File
	file_pinguin_proto_goTypes = nil
	file_pinguin_proto_depIdxs = nil
}
